### PR TITLE
Add method to manually switch to next/prev screen

### PR DESCRIPTION
**Pull request by boformer**
* Adds the 2 methods
* Adds a wizard getter in Screen class (to make the methods accessible).

Use case: When the installation is finished, automatically go from "Installation Progress" to "Finish" screen.

2 minor fixes:

* Removes unused private description string in Screen
* javadoc spelling

### CODE REVIEW

**Comment by boformer** [comment]
> Why would you need that ?

I want to class wizard.nextScreen() from my screen class (where the user action happens).

I found a simple replacement for the getWizard() method. I will just put my Wizard into the data map, so the method is no longer neccessary for me.

**Comment by bflorat** [comment]
Maybe should we add a `screen.nextScreen()` / screen.prevScreen()` ? 
I found a way to perform a kind of callback to the wizard without having a direct dependency between the screen and the wizard (check my last commit, I use a Timer). The screen would register to the wizard a request for next/prev screen but has still none direct dependency neither to the Wizard class nor to its associated wizard instance.
What do you think ?

**Comment by boformer** [comment]
That would work.

**Comment by bflorat** [comment]
Done. I renamed the methods forceXXX() like forceNextScreen() and I added the same behavior for canceling and finishing. 

The manual has been updated accordingly at https://github.com/bflorat/qdwizard/blob/master/README.md#advanced-topics

**Pull request merged**
